package io.wulfcodes.messaging.chat.model.dto.request;

import io.wulfcodes.messaging.chat.model.vo.FrameType;

/**
 * Frame sent by a client over the WebSocket. Which fields are used depends on {@code type}:
 * <pre>
 * SEND   {"type":"SEND","conversationId":"01J..","clientMessageId":"c-42","body":"hi"}
 * READ   {"type":"READ","conversationId":"01J..","messageId":"1006..."}
 * TYPING {"type":"TYPING","conversationId":"01J..","typing":true}
 * </pre>
 *
 * @param clientMessageId id generated by the client, echoed in the ACK so it can match
 *                        its optimistic "sending..." bubble to the stored message
 */
public record ClientFrame(
        FrameType type,
        String conversationId,
        String clientMessageId,
        String body,
        String messageId,
        Boolean typing
) {
}
