package io.wulfcodes.messaging.chat.model.dto.request;

import io.wulfcodes.messaging.chat.model.vo.FrameType;

/**
 * Frame sent by a client over the WebSocket, e.g.
 * {"type":"SEND","conversationId":"01J...","clientMessageId":"c-42","body":"hi"}
 *
 * @param clientMessageId id generated by the client, echoed in the ACK so it can match
 *                        its optimistic "sending..." bubble to the stored message
 */
public record ClientFrame(
        FrameType type,
        String conversationId,
        String clientMessageId,
        String body
) {
}
